with-expecter: false
packages:
    github.com/jfelipearaujo-org/ms-payment-management/internal/environment:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/environment/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Environment)"
    github.com/jfelipearaujo-org/ms-payment-management/internal/adapter/database:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/adapter/database/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Service)"
    github.com/jfelipearaujo-org/ms-payment-management/internal/repository:
        config:
          filename: "{{ .InterfaceName | snakecase }}_mock.go"
          dir: "./internal/repository/mocks"
          mockname: "Mock{{.InterfaceName}}"
          outpkg: "mocks"
          include-regex: "(Repository)"