@host=http://localhost:8080

### Health Check
GET {{host}}/health
Content-Type: application/json

### Payment Webhook
PATCH {{host}}/api/v1/payments/webhook/9dfa1386-2f52-4cca-b9aa-f9bd6887d442
Content-Type: application/json

{
    "approved": false
}