apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-payment-management-ingress
  namespace: ns-payments
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/permanent-redirect-code: "308"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /payments-mgmt(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: ms-payment-management
                port:
                  number: 8080