apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ms-payment-management-ingress
  namespace: ns-payments
spec:
  rules:
    - http:
        paths:
          - path: /payments
            pathType: Prefix
            backend:
              service:
                name: ms-payment-management
                port:
                  number: 8080