apiVersion: v1
kind: Service
metadata:
  name: ms-payment-management
  namespace: ns-payments
  labels:
    app: ms-payment-management
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: ms-payment-management