// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	context "context"

	payment_entity "github.com/jfelipearaujo-org/ms-payment-management/internal/entity/payment_entity"
	mock "github.com/stretchr/testify/mock"
)

// MockCreatePaymentService is an autogenerated mock type for the CreatePaymentService type
type MockCreatePaymentService[T interface{}] struct {
	mock.Mock
}

// Handle provides a mock function with given fields: ctx, request
func (_m *MockCreatePaymentService[T]) Handle(ctx context.Context, request T) (*payment_entity.Payment, error) {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 *payment_entity.Payment
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) (*payment_entity.Payment, error)); ok {
		return rf(ctx, request)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) *payment_entity.Payment); ok {
		r0 = rf(ctx, request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*payment_entity.Payment)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(ctx, request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockCreatePaymentService creates a new instance of MockCreatePaymentService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCreatePaymentService[T interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCreatePaymentService[T] {
	mock := &MockCreatePaymentService[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
